# Install the application dependencies in a full UBI Node docker image
FROM registry.access.redhat.com/ubi8/nodejs-14:latest

# Copy package.json and package-lock.json
COPY . ./

# Install app dependencies
RUN npm install 

# Build production static files to /dist
RUN npm run build

# Copy the dependencies into a minimal Node.js image
FROM registry.redhat.io/rhel8/nginx-118:1-48

USER 0
COPY /dist /tmp/src/
RUN chown -R 1001:0 /tmp/src
USER 1001

# Let the assemble script to install the dependencies
RUN /usr/libexec/s2i/assemble

# Run script uses standard ways to run the application
CMD /usr/libexec/s2i/run